### PR TITLE
Failed script transactions

### LINKED ISSUE #282: [V1.2]  Accept transactions with failed script result
**Аbstract**

**For more information see [WEP9](https://forum.wavesplatform.com/t/wep-9-accept-transactions-with-failed-script-result/19112).**

Transactions with failed scripts should be stored in blockchain. All transactions with valid sender signature should be stored on blockchain even if it's script execution leads to failure. Fee for storing such transactions should be paid by sender. 

**Motivation and Purposes**

Users of Waves blockchain can do non valid transactions without paying for it. Script execution is resource consuming operation, so transactions with failed scripts should be paid. 

**Specification**

Transaction application should work as follows:

1. Transaction's timestamp validation
2. Transaction's version check
3. Check sender's balance for available amount of spend assets
4. Check sender's balance for available amount to pay fees
5. Check transaction's proofs, execute verifying script
6. Build state modifications for transaction
6.1. For Invoke Transaction execute DApp script
6.2. Build all resulting Invoke actions
6.3. Execute Smart Assets scripts for all Invoke actions
6.4. Check sender's balance for availability of additional funds to pay actions' fees
6.5. Execute Smart Assets scripts for payments
6.6. Execute Smart Assets scripts for actions
7. Apply transaction

Changes to existing procedure:
1. Check sender's balance before scripts execution
2. Execute Smart Assets scripts after execution fo account script
3. Execute DApp script before execution of payment's script
4. Check sender's balance for availability of funds to pay additional fees for Invoke actions before execution of those actions scripts

Only Invoke and Exchange transactions should be stored if failed.

**Backwards Compatibility**

The ability to pay fee for DApp execution with funds received in attached payment will be broken.

### PR DESCRIPTION
**Pull request by alexeykiselev**
Closes #282, #291

### CODE REVIEW

File: pkg/state/appender.go [hunk 1]
```diff
@@ -396,28 +445,43 @@ func (a *txAppender) appendBlock(params *appendBlockParams) error {
...
 		if err != nil {
 			return err
 		}
 		a.recentTxIds[string(txID)] = empty
-		// Check against state.
-		txScriptsRuns, err := a.checkTxAgainstState(tx, accountHasVerifierScript, checkerInfo, blockInfo)
-		if err != nil {
-			return err
+		// After activation of AcceptFailedScriptTransactions feature we have to check availability of funds to
+		// pay fees for all transaction types except LeaseCancel.
```
Comment (zer0main) [inline pkg/state/appender.go:459]: My previous comment doubts this.

File: pkg/state/invoke_applier.go [hunk 2]
```diff
@@ -212,315 +212,333 @@ func (ia *invokeApplier) resolveAliases(actions []proto.ScriptAction, initialisa
...
-			return txBalanceChanges{}, errors.Wrap(err, "failed to convert fee asset to waves")
+			return nil, false, errors.Wrap(err, "failed to convert fee asset to waves")
 		}
 	}
 	if wavesFee < minWavesFee {
-		return txBalanceChanges{}, errors.Errorf("tx fee %d is less than minimum value of %d\n", wavesFee, minWavesFee)
+		return nil, false, errors.Errorf("tx fee %d is less than minimum value of %d\n", wavesFee, minWavesFee)
 	}
-	return totalChanges, nil
+	return totalChanges.addresses(), true, nil
```
Comment (zer0main) [inline pkg/state/invoke_applier.go:523]: Looks like this function returns `true` when Invoke actually failed. Am I wrong about it?

File: pkg/state/block_differ.go [hunk 3]
```diff
@@ -110,20 +110,34 @@ func (d *blockDiffer) createPrevBlockMinerFeeDiff(prevBlockID proto.BlockID, min
...
 	if err != nil {
 		return txBalanceChanges{}, err
 	}
 	differInfo := &differInfo{initialisation, blockInfo}
-	txChanges, err := d.handler.createDiffTx(tx, differInfo)
+	var txChanges txBalanceChanges
+	if status {
+		txChanges, err = d.handler.createDiffTx(tx, differInfo)
+	} else {
+		txChanges, err = d.handler.createFeeDiffTx(tx, differInfo)
```
Comment (zer0main) [inline pkg/state/block_differ.go:123]: Looks like `createFeeDiff` is only needed for Invoke and Exchange, since it is called when `status` is false.
